"""build_web_data.py — bundle the analysis into the offline dashboard.

Reads `deliverables/analysis.json` (produced by `python -m saleskpi
--deliverables`) and writes `web/data.js` as a plain assignment:

    window.ANALYSIS = { ... };

That lets `web/index.html` open straight from disk (file://) with no server,
no fetch, and no CDN — the whole dashboard is self-contained.

    python scripts/build_web_data.py

Author: Dimitres Kisimov.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ANALYSIS = ROOT / "deliverables" / "analysis.json"
OUT = ROOT / "web" / "data.js"


def main() -> int:
    if not ANALYSIS.exists():
        raise SystemExit(
            "deliverables/analysis.json not found — run "
            "`python -m saleskpi --deliverables` first."
        )
    data = json.loads(ANALYSIS.read_text(encoding="utf-8"))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(data, indent=2, ensure_ascii=False)
    banner = (
        "// AUTO-GENERATED by scripts/build_web_data.py — do not edit by hand.\n"
        "// Source: deliverables/analysis.json\n"
    )
    OUT.write_text(f"{banner}window.ANALYSIS = {payload};\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
